package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/mhaynie/bats-declarative/src/dats/internal/schema"
	"gopkg.in/yaml.v3"
)

// Generator converts .dats files to .bats files
type Generator struct {
	InputPath  string
	OutputDir  string
	RuntimeDir string // Path to runtime/ directory with test_helper.bash
}

// Result contains the generated files
type Result struct {
	BatsFile   string            // Path to generated .bats file
	DepFile    string            // Path to generated .d dependency file
	InputFiles map[string]string // Map of fixture files to create (path -> content)
}

// Generate parses the input .dats file and generates BATS tests
func (g *Generator) Generate() (*Result, error) {
	// Read and parse the input file
	data, err := os.ReadFile(g.InputPath)
	if err != nil {
		return nil, fmt.Errorf("reading input file: %w", err)
	}

	var testFile schema.TestFile
	if err := yaml.Unmarshal(data, &testFile); err != nil {
		return nil, fmt.Errorf("parsing YAML: %w", err)
	}

	// Generate output paths
	baseName := strings.TrimSuffix(filepath.Base(g.InputPath), ".dats")
	batsPath := filepath.Join(g.OutputDir, baseName+".gen.bats")
	depPath := filepath.Join(g.OutputDir, baseName+".gen.bats.d")

	// Generate the BATS content
	batsContent, inputFiles, err := g.generateBats(&testFile, baseName)
	if err != nil {
		return nil, fmt.Errorf("generating BATS: %w", err)
	}

	// Write the BATS file
	if err := os.WriteFile(batsPath, []byte(batsContent), 0644); err != nil {
		return nil, fmt.Errorf("writing BATS file: %w", err)
	}

	// Generate and write the dependency file
	depContent := g.generateDepFile(batsPath, g.InputPath, inputFiles)
	if err := os.WriteFile(depPath, []byte(depContent), 0644); err != nil {
		return nil, fmt.Errorf("writing dep file: %w", err)
	}

	// Write input fixture files
	for path, content := range inputFiles {
		fullPath := filepath.Join(g.OutputDir, path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return nil, fmt.Errorf("creating fixture dir: %w", err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return nil, fmt.Errorf("writing fixture file %s: %w", path, err)
		}
	}

	return &Result{
		BatsFile:   batsPath,
		DepFile:    depPath,
		InputFiles: inputFiles,
	}, nil
}

func (g *Generator) generateBats(testFile *schema.TestFile, baseName string) (string, map[string]string, error) {
	var buf strings.Builder
	inputFiles := make(map[string]string)

	// Write header
	buf.WriteString("#!/usr/bin/env bats\n")
	buf.WriteString("# Generated by dats - DO NOT EDIT\n\n")

	// Calculate relative path to runtime directory from output directory
	relRuntime, err := filepath.Rel(g.OutputDir, g.RuntimeDir)
	if err != nil {
		relRuntime = g.RuntimeDir
	}

	buf.WriteString(fmt.Sprintf("load \"%s/test_helper\"\n\n", relRuntime))

	// Generate each test
	for i, test := range testFile.Tests {
		testContent, files, err := g.generateTest(&test, baseName, i)
		if err != nil {
			return "", nil, fmt.Errorf("generating test %q: %w", test.Desc, err)
		}
		buf.WriteString(testContent)
		buf.WriteString("\n")

		for k, v := range files {
			inputFiles[k] = v
		}
	}

	return buf.String(), inputFiles, nil
}

func (g *Generator) generateTest(test *schema.Test, baseName string, index int) (string, map[string]string, error) {
	var buf strings.Builder
	inputFiles := make(map[string]string)

	// Test function declaration - use desc if provided, otherwise use cmd
	testName := test.Desc
	if testName == "" {
		testName = test.Cmd
	}
	buf.WriteString(fmt.Sprintf("@test %q {\n", testName))

	// Create fixture directory for this test
	fixtureDir := fmt.Sprintf("fixtures/%s/%d", baseName, index)

	// Process inputs - create fixture files
	inputPaths := make(map[string]string) // input name -> fixture path
	for name, content := range test.Inputs {
		fixturePath := filepath.Join(fixtureDir, "inputs", name)
		inputFiles[fixturePath] = content
		inputPaths[name] = fixturePath
	}

	// Create output file paths
	outputPaths := make(map[string]string) // output name -> path
	for name := range test.Outputs.Files {
		outputPaths[name] = filepath.Join(fixtureDir, "outputs", name)
	}

	// Expand placeholders in command
	cmd := expandPlaceholders(test.Cmd, inputPaths, outputPaths, g.OutputDir)

	// Setup: create output directories if needed
	if len(outputPaths) > 0 {
		outputDir := filepath.Join(fixtureDir, "outputs")
		buf.WriteString(fmt.Sprintf("  mkdir -p \"$BATS_TEST_DIRNAME/%s\"\n", outputDir))
	}

	// Generate the run command
	if test.Stdin != "" {
		// Pipe stdin to command using here-string
		escapedStdin := bashEscape(test.Stdin)
		// Use here-string (<<<) to provide stdin
		buf.WriteString(fmt.Sprintf("  run bash -c %s <<< %s\n", bashEscapeDouble(cmd), escapedStdin))
	} else {
		buf.WriteString(fmt.Sprintf("  run %s\n", cmd))
	}

	// Assert exit code
	buf.WriteString(fmt.Sprintf("  assert_exit_code %s\n", test.Exit.String()))

	// Generate stdout assertions
	generateOutputAssertions(&buf, "output", test.Outputs.Stdout, false)
	generateOutputAssertions(&buf, "output", test.Outputs.NotStdout, true)

	// Generate stderr assertions (BATS doesn't capture stderr separately by default)
	// We'll handle this via a custom helper
	if !test.Outputs.Stderr.IsEmpty() || !test.Outputs.NotStderr.IsEmpty() {
		// For stderr, we need to modify the run command - this is a limitation
		// For now, we'll add a note that stderr checking requires special handling
		buf.WriteString("  # Note: stderr assertions require capturing stderr separately\n")
	}

	// Generate output file assertions
	for name, check := range test.Outputs.Files {
		path := filepath.Join("$BATS_TEST_DIRNAME", fixtureDir, "outputs", name)

		if check.Exists != nil {
			if *check.Exists {
				buf.WriteString(fmt.Sprintf("  [ -f \"%s\" ]\n", path))
			} else {
				buf.WriteString(fmt.Sprintf("  [ ! -f \"%s\" ]\n", path))
			}
		}

		for _, pattern := range check.Contains {
			buf.WriteString(fmt.Sprintf("  grep -q %s \"%s\"\n", bashEscape(pattern), path))
		}
	}

	buf.WriteString("}\n")

	return buf.String(), inputFiles, nil
}

func generateOutputAssertions(buf *strings.Builder, varName string, check schema.OutputCheck, negative bool) {
	// Pattern assertions
	for _, pattern := range check.Patterns {
		if negative {
			buf.WriteString(fmt.Sprintf("  refute_output --partial %s\n", bashEscape(pattern)))
		} else {
			buf.WriteString(fmt.Sprintf("  assert_output --partial %s\n", bashEscape(pattern)))
		}
	}

	// Line-specific assertions
	if len(check.LineChecks) > 0 {
		// Sort line numbers for consistent output
		lines := make([]int, 0, len(check.LineChecks))
		for line := range check.LineChecks {
			lines = append(lines, line)
		}
		sort.Ints(lines)

		for _, line := range lines {
			pattern := check.LineChecks[line]
			if negative {
				buf.WriteString(fmt.Sprintf("  refute_line --index %d --regexp %s\n", line, bashEscape(pattern)))
			} else {
				buf.WriteString(fmt.Sprintf("  assert_line --index %d --regexp %s\n", line, bashEscape(pattern)))
			}
		}
	}
}

// expandPlaceholders replaces {inputs.X} and {outputs.X} with actual paths
func expandPlaceholders(cmd string, inputPaths, outputPaths map[string]string, baseDir string) string {
	// Replace {inputs.X}
	inputRe := regexp.MustCompile(`\{inputs\.([^}]+)\}`)
	cmd = inputRe.ReplaceAllStringFunc(cmd, func(match string) string {
		name := inputRe.FindStringSubmatch(match)[1]
		if path, ok := inputPaths[name]; ok {
			return fmt.Sprintf("\"$BATS_TEST_DIRNAME/%s\"", path)
		}
		return match // Keep original if not found
	})

	// Replace {outputs.X}
	outputRe := regexp.MustCompile(`\{outputs\.([^}]+)\}`)
	cmd = outputRe.ReplaceAllStringFunc(cmd, func(match string) string {
		name := outputRe.FindStringSubmatch(match)[1]
		if path, ok := outputPaths[name]; ok {
			return fmt.Sprintf("\"$BATS_TEST_DIRNAME/%s\"", path)
		}
		return match // Keep original if not found
	})

	return cmd
}

// bashEscape escapes a string for use in bash using $'...' syntax
func bashEscape(s string) string {
	escaped := strings.ReplaceAll(s, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "'", "\\'")
	escaped = strings.ReplaceAll(escaped, "\n", "\\n")
	escaped = strings.ReplaceAll(escaped, "\t", "\\t")
	return "$'" + escaped + "'"
}

// bashEscapeDouble escapes a string for use in double quotes
func bashEscapeDouble(s string) string {
	escaped := strings.ReplaceAll(s, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
	escaped = strings.ReplaceAll(escaped, "$", "\\$")
	escaped = strings.ReplaceAll(escaped, "`", "\\`")
	return "\"" + escaped + "\""
}

func (g *Generator) generateDepFile(batsPath, inputPath string, inputFiles map[string]string) string {
	var deps []string
	deps = append(deps, inputPath)

	for path := range inputFiles {
		deps = append(deps, filepath.Join(g.OutputDir, path))
	}

	return fmt.Sprintf("%s: %s\n", batsPath, strings.Join(deps, " "))
}
