// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// ExitCode ...
type ExitCode string

// LineCheck ...
type LineCheck struct {
	NAttr int    `xml:"n,attr"`
	Value string `xml:",chardata"`
}

// StreamCheck ...
type StreamCheck struct {
	Match    []string     `xml:"match"`
	NotMatch []string     `xml:"not-match"`
	Line     []*LineCheck `xml:"line"`
}

// InputFile ...
type InputFile struct {
	NameAttr string `xml:"name,attr"`
	Value    string `xml:",chardata"`
}

// FileOutput ...
type FileOutput struct {
	NameAttr   string   `xml:"name,attr"`
	ExistsAttr *bool    `xml:"exists,attr"`
	Match      []string `xml:"match"`
	NotMatch   []string `xml:"not-match"`
}

// Test ...
type Test struct {
	DescAttr *string       `xml:"desc,attr"`
	CmdAttr  string        `xml:"cmd,attr"`
	ExitAttr *ExitCode     `xml:"exit,attr,omitempty"`
	Stdin    *string       `xml:"stdin"`
	Input    []*InputFile  `xml:"input"`
	Stdout   *StreamCheck  `xml:"stdout"`
	Stderr   *StreamCheck  `xml:"stderr"`
	Output   []*FileOutput `xml:"output"`
}

// Dats ...
type Dats struct {
	XMLName xml.Name `xml:"dats"`
	Test    []*Test  `xml:"test"`
}
