# DATS VS Code Extension

# Build extension and package as .vsix
build: _compile
    mkdir -p "$BUILD_DIR"
    npx vsce package --out "$BUILD_DIR/dats.vsix"

# Install extension in VS Code
install: build
    code --install-extension "$BUILD_DIR/dats.vsix" --force

# Update dependencies to latest versions
update:
    npx npm-check-updates -u
    npm install

# Run tests
test:
    npx vitest run --coverage

_compile: _deps
    npx esbuild src/extension.ts --bundle --minify --outfile=dist/extension.js --external:vscode --format=cjs --platform=node
    npx esbuild src/extension.ts --bundle --minify --outfile=dist/web/extension.js --external:vscode --format=cjs --platform=browser

_deps:
    npm install
